// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Parse, validate, and VERIFY a VaultBackup JSON string.
///
/// Reconstructs the vault from raw key material and verifies the address matches.
/// If verification fails, returns an error — the backup may be corrupt or tampered.
Future<VaultInfo> importVaultBackup({required String json}) =>
    RustLib.instance.api.crateApiImportVaultBackup(json: json);

/// Check if an heir is eligible to claim based on current block height.
Future<ClaimEligibility> checkEligibility({
  required String vaultJson,
  required BigInt currentHeight,
  required BigInt confirmationHeight,
}) => RustLib.instance.api.crateApiCheckEligibility(
  vaultJson: vaultJson,
  currentHeight: currentHeight,
  confirmationHeight: confirmationHeight,
);

/// Validate a Bitcoin address string for the given network.
Future<bool> validateAddress({
  required String address,
  required String network,
}) => RustLib.instance.api.crateApiValidateAddress(
  address: address,
  network: network,
);

/// Claim eligibility status.
class ClaimEligibility {
  final bool eligible;
  final PlatformInt64 blocksRemaining;
  final double daysRemaining;

  const ClaimEligibility({
    required this.eligible,
    required this.blocksRemaining,
    required this.daysRemaining,
  });

  @override
  int get hashCode =>
      eligible.hashCode ^ blocksRemaining.hashCode ^ daysRemaining.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClaimEligibility &&
          runtimeType == other.runtimeType &&
          eligible == other.eligible &&
          blocksRemaining == other.blocksRemaining &&
          daysRemaining == other.daysRemaining;
}

/// Vault summary returned after parsing and verifying a VaultBackup JSON.
class VaultInfo {
  final String network;
  final String vaultAddress;
  final int timelockBlocks;
  final BigInt heirCount;
  final List<String> heirLabels;
  final bool hasRecoveryLeaves;
  final bool addressVerified;

  const VaultInfo({
    required this.network,
    required this.vaultAddress,
    required this.timelockBlocks,
    required this.heirCount,
    required this.heirLabels,
    required this.hasRecoveryLeaves,
    required this.addressVerified,
  });

  @override
  int get hashCode =>
      network.hashCode ^
      vaultAddress.hashCode ^
      timelockBlocks.hashCode ^
      heirCount.hashCode ^
      heirLabels.hashCode ^
      hasRecoveryLeaves.hashCode ^
      addressVerified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultInfo &&
          runtimeType == other.runtimeType &&
          network == other.network &&
          vaultAddress == other.vaultAddress &&
          timelockBlocks == other.timelockBlocks &&
          heirCount == other.heirCount &&
          heirLabels == other.heirLabels &&
          hasRecoveryLeaves == other.hasRecoveryLeaves &&
          addressVerified == other.addressVerified;
}
