// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1468179889;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'nostring_heir_ffi',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<ClaimPsbt> crateApiBuildClaimPsbt({
    required String vaultJson,
    required String electrumUrl,
    required String destinationAddress,
    required BigInt heirIndex,
    required BigInt feeRateSatVb,
  });

  Future<ClaimEligibility> crateApiCheckEligibility({
    required String vaultJson,
    required BigInt currentHeight,
    required BigInt confirmationHeight,
  });

  Future<VaultStatus> crateApiFetchVaultStatus({
    required String vaultJson,
    required String electrumUrl,
  });

  Future<VaultInfo> crateApiImportVaultBackup({required String json});

  Future<bool> crateApiValidateAddress({
    required String address,
    required String network,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<ClaimPsbt> crateApiBuildClaimPsbt({
    required String vaultJson,
    required String electrumUrl,
    required String destinationAddress,
    required BigInt heirIndex,
    required BigInt feeRateSatVb,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultJson, serializer);
          sse_encode_String(electrumUrl, serializer);
          sse_encode_String(destinationAddress, serializer);
          sse_encode_usize(heirIndex, serializer);
          sse_encode_u_64(feeRateSatVb, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_claim_psbt,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBuildClaimPsbtConstMeta,
        argValues: [
          vaultJson,
          electrumUrl,
          destinationAddress,
          heirIndex,
          feeRateSatVb,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBuildClaimPsbtConstMeta => const TaskConstMeta(
    debugName: "build_claim_psbt",
    argNames: [
      "vaultJson",
      "electrumUrl",
      "destinationAddress",
      "heirIndex",
      "feeRateSatVb",
    ],
  );

  @override
  Future<ClaimEligibility> crateApiCheckEligibility({
    required String vaultJson,
    required BigInt currentHeight,
    required BigInt confirmationHeight,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultJson, serializer);
          sse_encode_u_64(currentHeight, serializer);
          sse_encode_u_64(confirmationHeight, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_claim_eligibility,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCheckEligibilityConstMeta,
        argValues: [vaultJson, currentHeight, confirmationHeight],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCheckEligibilityConstMeta => const TaskConstMeta(
    debugName: "check_eligibility",
    argNames: ["vaultJson", "currentHeight", "confirmationHeight"],
  );

  @override
  Future<VaultStatus> crateApiFetchVaultStatus({
    required String vaultJson,
    required String electrumUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultJson, serializer);
          sse_encode_String(electrumUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vault_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFetchVaultStatusConstMeta,
        argValues: [vaultJson, electrumUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFetchVaultStatusConstMeta => const TaskConstMeta(
    debugName: "fetch_vault_status",
    argNames: ["vaultJson", "electrumUrl"],
  );

  @override
  Future<VaultInfo> crateApiImportVaultBackup({required String json}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vault_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImportVaultBackupConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImportVaultBackupConstMeta =>
      const TaskConstMeta(debugName: "import_vault_backup", argNames: ["json"]);

  @override
  Future<bool> crateApiValidateAddress({
    required String address,
    required String network,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          sse_encode_String(network, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiValidateAddressConstMeta,
        argValues: [address, network],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiValidateAddressConstMeta => const TaskConstMeta(
    debugName: "validate_address",
    argNames: ["address", "network"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ClaimEligibility dco_decode_claim_eligibility(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ClaimEligibility(
      eligible: dco_decode_bool(arr[0]),
      blocksRemaining: dco_decode_i_64(arr[1]),
      daysRemaining: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  ClaimPsbt dco_decode_claim_psbt(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ClaimPsbt(
      psbtBase64: dco_decode_String(arr[0]),
      totalInputSat: dco_decode_u_64(arr[1]),
      feeSat: dco_decode_u_64(arr[2]),
      outputSat: dco_decode_u_64(arr[3]),
      destination: dco_decode_String(arr[4]),
      numInputs: dco_decode_usize(arr[5]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VaultInfo dco_decode_vault_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return VaultInfo(
      network: dco_decode_String(arr[0]),
      vaultAddress: dco_decode_String(arr[1]),
      timelockBlocks: dco_decode_u_16(arr[2]),
      heirCount: dco_decode_usize(arr[3]),
      heirLabels: dco_decode_list_String(arr[4]),
      hasRecoveryLeaves: dco_decode_bool(arr[5]),
      addressVerified: dco_decode_bool(arr[6]),
    );
  }

  @protected
  VaultStatus dco_decode_vault_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return VaultStatus(
      balanceSat: dco_decode_u_64(arr[0]),
      utxoCount: dco_decode_usize(arr[1]),
      currentHeight: dco_decode_u_64(arr[2]),
      confirmationHeight: dco_decode_u_64(arr[3]),
      eligible: dco_decode_bool(arr[4]),
      blocksRemaining: dco_decode_i_64(arr[5]),
      daysRemaining: dco_decode_f_64(arr[6]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ClaimEligibility sse_decode_claim_eligibility(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_eligible = sse_decode_bool(deserializer);
    var var_blocksRemaining = sse_decode_i_64(deserializer);
    var var_daysRemaining = sse_decode_f_64(deserializer);
    return ClaimEligibility(
      eligible: var_eligible,
      blocksRemaining: var_blocksRemaining,
      daysRemaining: var_daysRemaining,
    );
  }

  @protected
  ClaimPsbt sse_decode_claim_psbt(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_psbtBase64 = sse_decode_String(deserializer);
    var var_totalInputSat = sse_decode_u_64(deserializer);
    var var_feeSat = sse_decode_u_64(deserializer);
    var var_outputSat = sse_decode_u_64(deserializer);
    var var_destination = sse_decode_String(deserializer);
    var var_numInputs = sse_decode_usize(deserializer);
    return ClaimPsbt(
      psbtBase64: var_psbtBase64,
      totalInputSat: var_totalInputSat,
      feeSat: var_feeSat,
      outputSat: var_outputSat,
      destination: var_destination,
      numInputs: var_numInputs,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VaultInfo sse_decode_vault_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_network = sse_decode_String(deserializer);
    var var_vaultAddress = sse_decode_String(deserializer);
    var var_timelockBlocks = sse_decode_u_16(deserializer);
    var var_heirCount = sse_decode_usize(deserializer);
    var var_heirLabels = sse_decode_list_String(deserializer);
    var var_hasRecoveryLeaves = sse_decode_bool(deserializer);
    var var_addressVerified = sse_decode_bool(deserializer);
    return VaultInfo(
      network: var_network,
      vaultAddress: var_vaultAddress,
      timelockBlocks: var_timelockBlocks,
      heirCount: var_heirCount,
      heirLabels: var_heirLabels,
      hasRecoveryLeaves: var_hasRecoveryLeaves,
      addressVerified: var_addressVerified,
    );
  }

  @protected
  VaultStatus sse_decode_vault_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_balanceSat = sse_decode_u_64(deserializer);
    var var_utxoCount = sse_decode_usize(deserializer);
    var var_currentHeight = sse_decode_u_64(deserializer);
    var var_confirmationHeight = sse_decode_u_64(deserializer);
    var var_eligible = sse_decode_bool(deserializer);
    var var_blocksRemaining = sse_decode_i_64(deserializer);
    var var_daysRemaining = sse_decode_f_64(deserializer);
    return VaultStatus(
      balanceSat: var_balanceSat,
      utxoCount: var_utxoCount,
      currentHeight: var_currentHeight,
      confirmationHeight: var_confirmationHeight,
      eligible: var_eligible,
      blocksRemaining: var_blocksRemaining,
      daysRemaining: var_daysRemaining,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_claim_eligibility(
    ClaimEligibility self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.eligible, serializer);
    sse_encode_i_64(self.blocksRemaining, serializer);
    sse_encode_f_64(self.daysRemaining, serializer);
  }

  @protected
  void sse_encode_claim_psbt(ClaimPsbt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.psbtBase64, serializer);
    sse_encode_u_64(self.totalInputSat, serializer);
    sse_encode_u_64(self.feeSat, serializer);
    sse_encode_u_64(self.outputSat, serializer);
    sse_encode_String(self.destination, serializer);
    sse_encode_usize(self.numInputs, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_vault_info(VaultInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.network, serializer);
    sse_encode_String(self.vaultAddress, serializer);
    sse_encode_u_16(self.timelockBlocks, serializer);
    sse_encode_usize(self.heirCount, serializer);
    sse_encode_list_String(self.heirLabels, serializer);
    sse_encode_bool(self.hasRecoveryLeaves, serializer);
    sse_encode_bool(self.addressVerified, serializer);
  }

  @protected
  void sse_encode_vault_status(VaultStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.balanceSat, serializer);
    sse_encode_usize(self.utxoCount, serializer);
    sse_encode_u_64(self.currentHeight, serializer);
    sse_encode_u_64(self.confirmationHeight, serializer);
    sse_encode_bool(self.eligible, serializer);
    sse_encode_i_64(self.blocksRemaining, serializer);
    sse_encode_f_64(self.daysRemaining, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
